### PR TITLE
Failure if best_elem is root (fix #58)

### LINKED ISSUE #58: Failure if best_elem is root
I have some documents that are raising the following exception
```
Traceback (most recent call last):
...
  File ".../site-packages/readability/readability.py", line 168, in summary
    html_partial=html_partial)
  File ".../site-packages/readability/readability.py", line 214, in get_article
    for sibling in best_elem.getparent().getchildren():
Unparseable: 'NoneType' object has no attribute 'getchildren'
```

I assume there should be a fix along the lines of:
```python
if best_elem.getparent() is None:
    siblings = [best_elem]
else:
    siblings = best_elem.getparent().getchildren()
for sibling in siblings:
```

### PR DESCRIPTION
**Pull request by avalanchy**
Reproduces and fixes issue https://github.com/buriy/python-readability/issues/58

### CODE REVIEW

**Comment by avalanchy** [comment]
@buriy: I just wanna pin on this change to my project. Can I expect release to pypi in this week? If not I will just reference this directly from github.

**Comment by buriy** [comment]
Yes, I'll do a release 0.6 by the end of the week (most probably, tomorrow) after checking if all the changes work fine and fixing several remaining logging issues.
I'll make a release 0.5.1 with this change right now.

**Comment by buriy** [comment]
".../python-readability/readability/readability.py:216: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  siblings = parent.getchildren() if parent else [best_elem]"
Fixed that.

**Comment by avalanchy** [comment]
It just build up with my project. Thanks!

**Pull request merged**
