### PR TITLE
Return score.

### PR DESCRIPTION
**Pull request by maomao905**
It would be better to return score, which is useful to know how confident extracted content is.

### CODE REVIEW

**Comment by buriy** [comment]
This is a good idea, but please add a different summary_with_score method which will do what you want and the current method should stay the same for compatibility.

**Comment by maomao905** [comment]
ok, I added summary_with_score method.

**Comment by buriy** [comment]
Thanks, I'll commit it asap (not updating it automatically because of failing builds).

**Comment by maomao905** [comment]
I found a bug in my code.
It should return 0.0 when best_candidate is None.

> I'll commit it asap (not updating it automatically because of failing builds)

Thanks.

**Comment by maomao905** [comment]
@buriy What is the status of the PR? I will appreciate if you merge this.

**Pull request closed without merging**
