### PR TITLE
Makeover for the README

### PR DESCRIPTION
**Pull request by lwm**
- [x] move to ~~markdown~~ restructured text
- [x] bring a simple, working example

View it [here](https://github.com/lwm/python-readability/blob/82837e4b5c92709e63a473bced2a4e6dc8f6ad4d/README.rst).

I chopped out some stuff, shout and I'll add what you want back in.

### CODE REVIEW

**Comment by buriy** [comment]
Thanks! Does it work with pypi? https://pypi.python.org/pypi/readability-lxml

**Comment by lwm** [comment]
> Does it work with pypi?

Oh, I see pypi only supports `Restructured Text` (Ref https://github.com/pypa/readme_renderer/pull/3). 

So, no, it won't work.

I could reformat if you want? It's no biggie, I suppose.

**Comment by buriy** [comment]
I believe there was a way to do it in setup.py :
long_description=open("README").read()
at https://github.com/buriy/python-readability/blob/master/setup.py#L22
If you could elaborate on that, we can switch from the current format.

**Comment by lwm** [comment]
> I believe there was a way to do it in setup.py :
> long_description=open("README").read()

I don't think pypi can render markdown correctly yet. In order to have it look render nicely on both github and pypi, we would need to use restructured text.

I ran:
```
pandoc --from=markdown --to=rst README.md -o README.rst
```

If you're not interested in that format, no stress ;)

**Pull request merged**
