### PR TITLE
Video

### PR DESCRIPTION
**Pull request by mgalves**
Let youtube and vimeo videos in cleaned HTML

Fixes null title bug

### CODE REVIEW

**Comment by benbeadle** [comment]
Any updates on supporting videos?

Keep up the good work!

**Comment by dhamaniasad** [comment]
Any updates on this? Supporting videos in the cleaned HTML would be an awesome feature to have.

**Comment by buriy** [comment]
I didn't have plans to support this, but, based on the user requests, I'll revise this pull request in the next 2 weeks.

**Comment by dhamaniasad** [comment]
@buriy Any updates on this?

**Comment by buriy** [comment]
I'm preparing Python3-compatible branch, wanted to add it there -- and that one is still not ready,
but I can merge this pull request into the current version today.
The pull request itself is fine.

**Comment by dhamaniasad** [comment]
Thanks :)

**Comment by buriy** [comment]
Merged.

**Comment by buriy** [comment]
@dhamaniasad @benbeadle @mgalves 
Please let me know if it works fine, maybe suggest a test sample -- I have no test for this yet!

**Comment by dhamaniasad** [comment]
@buriy I tested this on a few webpages, and it seems to be failing on some of them. An example would be [this](http://www.sciencedump.com/content/science-behind-avengers-powers) url. I checked at https://github.com/buriy/python-readability/blob/master/readability/readability.py#L435-439 on runtime, and it doesn't drop the iframe element there, but it produces [this](https://gist.github.com/dhamaniasad/6624a43c384dea5beb2f) output. It seems to be dropping the main parent div(the iframe is inside a mess of [nested divs](https://gist.github.com/dhamaniasad/16cfa3ba54df483abfb3)). I tried digging around to see where it was dropping the parent div element, but I have not yet found the source of this problem.

**Comment by buriy** [comment]
@dhamaniasad I guess it probably drops this iframe thinking that it has no text -- similarly it cuts ads, blocks of links and other embeddings.
If the iframe is before or after the text -- I think this is correct decision. If iframe is in the middle of the text -- we need to make a better fix rather than current one (we're adding "text": ```<iframe>text</iframe>```)
I'll add this example to the code on the next week.

**Comment by buriy** [comment]
Rechecked -- the doc is processed correctly.
Problem is that the video gets into a different subtree, and that's not the minimal subtree spanning over text:
$ python -m readability.readability -vv science-behind-avengers-powers
2015-07-27 11:00:44,843: INFO: Top 5 : 62.000 .small-12.large-8.columns>.field.field-name-body (at readability.py: 259)
2015-07-27 11:00:44,843: INFO: Top 5 : 21.761 .row.node.node-article.node-promoted.view-mode-full.clearfix>.small-12.large-8.columns (at readability.py: 259)

I'll add a graphical representation at some moment later, then I might be able to illustrate such kind of issues clearly -- at the moment the algorithm is very naive.
Another idea could be to add "support text", where you choose the best text containing node based on your custom scoring function. I use it in practice, and going to incorporate it into the next release.

**Pull request closed without merging**
