### PR TITLE
Extended travis config

### PR DESCRIPTION
**Pull request by adbar**
- Python versions added (3.9, pypy)
- OS added (MacOS, 2 different versions)

### CODE REVIEW

**Comment by buriy** [comment]
https://travis-ci.org/buriy/python-readability/jobs/642945501 doesn't work. Any ideas why?

**Comment by adbar** [comment]
The machine is running Python 3: https://travis-ci.org/buriy/python-readability/jobs/642945501#L80
But tox launches Python 2.7: https://travis-ci.org/buriy/python-readability/jobs/642945501#L163
I guess the mismatch of the two causes the error.

**Comment by adbar** [comment]
The other test passes but it's actually a dry run: https://travis-ci.org/buriy/python-readability/jobs/642945500#L164
The `tox.ini` file should be changed in order to make it work on Travis MacOS.

**Comment by buriy** [comment]
Do we need to add python executable explicitly maybe as we do for other platforms?
```
      python: ...
```

**Comment by adbar** [comment]
I got one version of macOS to work, for the second one I don't know.

**Comment by adbar** [comment]
Maybe it's a bug on Travis' side, it's curious that it doesn't work, even on Python 2.7.

**Comment by buriy** [comment]
Yes, I think it is -- I added "python: python3" option but it didn't work (but 3 lines above it worked), we need to call them, meanwhile, I'll accept this PR.
I think, before the next major release, I can run tox on my MacBook.

**Pull request merged**
