### PR TITLE
Fixed issue with self closing elements

### PR DESCRIPTION
**Pull request by azmeuk**
See #125 for details.

### CODE REVIEW

**Comment by azmeuk** [comment]
Thank you for merging everything so quickly. Do you plan do release 0.8 soon? I would really love to see this patch in production.

Éloi

**Comment by buriy** [comment]
Yes, I'm planning to release 0.8 today, once I'll check everything is working smoothly.

**Comment by azmeuk** [comment]
Great news!

**Comment by azmeuk** [comment]
Hello @buriy.
Did you manage to find some time to do a pypi release?

**Comment by buriy** [comment]
@azmeuk not yet.
I want to include a new feature that will be ready in several days. Then I will publish the release on pypi.

**Pull request merged**
